_wandb:
    value:
        cli_version: 0.23.1
        e:
            5ie0ncosh3peqr32b0zdotbeuoq260ad:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "15032385536000"
                        used: "81920"
                email: zhang_zhaowei@whu.edu.cn
                executable: /root/miniconda3/envs/alphazero/bin/python
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-da8742bf-63b2-b4e0-cfe5-d4d17ee5ff32
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-ea29768f-e48f-ce9f-f5d4-66d2ab66a985
                host: pt-0ff20aaf949543c18183963abf3df960-worker-0
                memory:
                    total: "2159555371008"
                os: Linux-5.14.0-284.25.1.el9_2.x86_64-x86_64-with-glibc2.35
                program: /data/share/lijiang/250010178/250010178/debug_tmp_6*6for4/train.py
                python: CPython 3.10.19
                root: /data/share/lijiang/250010178/250010178/debug_tmp_6*6for4
                startedAt: "2025-12-30T06:58:27.685641Z"
                writerId: 5ie0ncosh3peqr32b0zdotbeuoq260ad
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 64
board_size:
    value: 6
device:
    value: cuda
lr:
    value: 0.002
n_in_row:
    value: 4
